name: CMake

on: [push, pull_request, workflow_dispatch]

# env:
#   # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
#   BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        sudo apt install gcc-multilib g++-multilib
        sudo pip install empy pydronecan
    - name: Submodule update
      run: |
        git submodule update --init --recursive
    - name: Clone required repositories
      run: |
        cd ${{github.workspace}}/tests
        git clone --depth 1 https://github.com/dronecan/dronecan_dsdlc
        git clone --depth 1 --branch v1.13.0 https://github.com/google/googletest
    - name: Run test
      working-directory: ${{github.workspace}}/tests
      run: ./run_test.sh
  
